### ISSUE TITLE
Mongoose Connection must be a string

### ISSUE THREAD

**Issue by 413ph** [sggts04/PuzzleDash#9]
![image](https://user-images.githubusercontent.com/81858321/159531542-b00f51a9-5e85-4306-91d6-4c59cb599428.png)

Hi, I have encountered this error when running npm start. I did npm install dotenv and it doesnt help. Here is my env file :

![image](https://user-images.githubusercontent.com/81858321/159532308-000c8d8a-8365-4fa3-91d4-6d820d27601f.png)

**Comment by sggts04** [comment]
Remove the quotes around your variable in .env file

**Comment by 413ph** [comment]
Thanks mate, it works! 
I also noted that I have to convert my passwd into percentage encoding.
